[package]
name = "spindle-shell"
version = "0.1.0"
edition = "2021"

[dependencies]

bigdecimal = "0.3.0"
chrono = "0.4"
crossterm = "0.24.0"
num-bigint = "0.4.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
